name: "Execute ATS Action"

on:
  push:
    branches:
      - main

jobs:
  ats_action:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install Python and pip"
        run: |
          sudo apt update
          sudo apt install python3-pip -y

      - name: "Verify package.txt exists"
        run: |
          if [ ! -f package.txt ]; then
            echo "package.txt not found. Failing the build."
            exit 1
          fi

      - name: "Install Python requirements"
        run: pip3 install --upgrade -r package.txt

      - name: "Run Flask app in background"
        run: |
          nohup python3 my_ats_checker.py > flask.log 2>&1 &
          echo "Flask app started in background..."

      - name: "Wait and test endpoint"
        run: |
          sleep 10
          curl --fail http://127.0.0.1:5000 || (echo "Flask app did not respond" && exit 1)

      - name: "Stop Flask app"
        run: |
          pkill -f my_ats_checker.py || echo "Flask app already stopped"
